export class SaleListing {
    id:Number;
    mls_id:String;
    status:Number;
    list_date:Date;
    sold_date:Date;
    last_fetched_status:Date;
    days_on_market:Number;
    expected_return_rate:Number;
    asking_price:Number;
    closing_price:Number;
    taxes:Number;
    address:String;
    postal:String;
    longitude:Number;
    latitude:Number;
    home_type:Number;
    home_style:Number;
    rooms_total:Number;
    family_rooms:Number;
    bedrooms:Number;
    washrooms:Number;
    kitchens:Number;
    basement_type:Number;
    basement_rooms:Number;
    basement_bedrooms:Number;
    basement_washrooms:Number;
    basement_kitchens:Number;
    heat_type:String;
    air_conditioner:String;
    sqft_from:Number;
    sqft_to:Number;
    num_of_stories:Number;
    parking_spaces:Number;
    garage:String;
    lot_length:Number;
    lot_width:Number;
    apx_age:String;
    ammenities:String;
    pool:String;
    water:String;
    sewer:String;
    exterior:String;
    ammenities_near_by:String;
    cross_streets:String;
    remarks:String;
    extras:String;
    raw_data:Object;
    created_at:Date;
    updated_at:Date;

    constructor(jsonObj = null) {
        if (jsonObj != null) {
            this.id = jsonObj.id;
            this.mls_id = jsonObj.mls_id;
            this.status = jsonObj.status;
            this.list_date = jsonObj.list_date;
            this.sold_date = jsonObj.sold_date;
            this.last_fetched_status = jsonObj.last_fetched_status;
            this.days_on_market = jsonObj.days_on_market;
            this.expected_return_rate = jsonObj.expected_return_rate;
            this.asking_price = jsonObj.asking_price;
            this.closing_price = jsonObj.closing_price;
            this.taxes = jsonObj.taxes;
            this.address = jsonObj.address;
            this.postal = jsonObj.postal;
            this.longitude = jsonObj.longitude;
            this.latitude = jsonObj.latitude;
            this.home_type = jsonObj.home_type;
            this.home_style = jsonObj.home_style;
            this.rooms_total = jsonObj.rooms_total;
            this.family_rooms = jsonObj.family_rooms;
            this.bedrooms = jsonObj.bedrooms;
            this.washrooms = jsonObj.washrooms;
            this.kitchens = jsonObj.kitchens;
            this.basement_type = jsonObj.basement_type;
            this.basement_rooms = jsonObj.basement_rooms;
            this.basement_bedrooms = jsonObj.basement_bedrooms;
            this.basement_washrooms = jsonObj.basement_washrooms;
            this.basement_kitchens = jsonObj.basement_kitchens;
            this.heat_type = jsonObj.heat_type;
            this.air_conditioner = jsonObj.air_conditioner;
            this.sqft_from = jsonObj.sqft_from;
            this.sqft_to = jsonObj.sqft_to;
            this.num_of_stories = jsonObj.num_of_stories;
            this.parking_spaces = jsonObj.parking_spaces;
            this.garage = jsonObj.garage;
            this.lot_length = jsonObj.lot_length;
            this.lot_width = jsonObj.lot_width;
            this.apx_age = jsonObj.apx_age;
            this.ammenities = jsonObj.ammenities;
            this.pool = jsonObj.pool;
            this.water = jsonObj.water;
            this.sewer = jsonObj.sewer;
            this.exterior = jsonObj.exterior;
            this.ammenities_near_by = jsonObj.ammenities_near_by;
            this.cross_streets = jsonObj.cross_streets;
            this.remarks = jsonObj.remarks;
            this.extras = jsonObj.extras;
            this.raw_data = jsonObj.raw_data;
            this.created_at = jsonObj.created_at;
            this.updated_at = jsonObj.updated_at;

        }
    }
}
